#!/usr/bin/env python
# Python Example for Python GitHub Webhooks
# File: push-myrepo-master
import subprocess
import os

import git


curdir = os.path.dirname(os.path.abspath(__file__))
reporootdir = os.path.dirname(curdir)
gitdir = os.path.dirname(reporootdir)
docsdir = os.path.join(gitdir, 'docs')

g = git.cmd.Git(docsdir)
g.pull()
