#!/usr/bin/env python
# Python Example for Python GitHub Webhooks
# File: push-myrepo-master
import subprocess
import sys
import json
import os

import git


curdir = os.path.dirname(os.path.abspath(__file__))


g = git.cmd.Git(curdir)
g.pull()


subp = subprocess.Popen(['git', 'pull'], cwd=curdir, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
subp.wait()
